const c=[
  {id: '1', name: 'KTOWN Pharma', date: '2025-11-15', online: 21, deleted: 0, link: 'https://chat.gta.world/?invite=6AAtoXfqHbFDDvR', about: 'PREMIUM Pharmaceuticals and MEDICAL Cannabis Market ❌ADVERTISING=BAN. ✅PRIVATE VENDORS. ✅QUALITY GUARANTEED. ✅DISCREET.'},
  {id: '2', name: 'Extreme Lane [TRUSTED VENDORS]', date: '2025-08-27', online: 75, deleted: 7, link: 'https://chat.gta.world/?invite=bBmNqsrGipW5TBG', about: 'TRUSTED VENDORS PAY 15K DEPOSIT FOR SCAM INSURANCE. BUSINESS VIA DMS.'},
  {id: '3', name: '[LSCHAT] LS VENDORS 💊☘️🧾💻💰', date: '2024-01-30', online: 178, deleted: 0, link: 'https://chat.gta.world/?invite=T5hGhdYT5Rb2bon', about: 'VENDORS MAY POST LISTINGS ONCE DAILY ONLY. ALL OTHER CONTENT IS FORBIDDEN AND CONTACT MUST BE THROUGH DMS OR FACE REMOVAL.'},
  {id: '4', name: 'south central vendors 💊☘️🧾💻💰', date: '2025-06-06', online: 102, deleted: 11, link: 'https://chat.gta.world/?invite=l95NZUxgzNtPqrs', about: ''},
  {id: '5', name: 'LS Strikers', date: '2024-06-12', online: 178, deleted: 19, link: 'https://chat.gta.world/?invite=SQHj7Ez5NTm6P7o', about: 'FORMER STREET RACING COMMUNITY. NOW UNDERGROUND MARKETPLACE.'},
  {id: '6', name: 'smashsomone.today', date: '2025-03-31', online: 95, deleted: 14, link: 'https://chat.gta.world/?invite=CUEzCkMLkhlOKiq', about: 'FORMERLY KNOWN AS "SMASHSOMONE.ONION". NOW UNDERGROUND MARKETPLACE.'},
  {id: '7', name: 'Coppermine', date: '2024-10-08', online: 174, deleted: 21, link: 'https://chat.gta.world/?invite=tPqQGpEPAl9zLj8', about: 'FORMERLY KNOWN AS "🎪 CIRCUS SHOP 🎪". NOW UNDERGROUND MARKETPLACE.'},
  {id: '8', name: 'VPN', date: '2025-01-15', online: 170, deleted: 20, link: 'https://chat.gta.world/?invite=Ea75OGSCWYEfJuw', about: ''},
  {id: '9', name: 'Trap House Recordz', date: '2024-11-25', online: 164, deleted: 20, link: 'https://chat.gta.world/?invite=hAJwB8QhmQ9cBX8', about: 'FORMERLY KNOWN AS "LS Dead Drops". NOW UNDERGROUND MARKETPLACE.'},
  {id: '10', name: 'Mexico Runz', date: '2025-05-15', online: 55, deleted: 7, link: 'https://chat.gta.world/?invite=q8UIRyFwwsQXH0k', about: 'FORMER STREET RACING COMMUNITY. NOW UNDERGROUND MARKETPLACE.'},
  {id: '11', name: '24', date: '2024-01-30', online: 16, deleted: 4, link: 'https://chat.gta.world/?invite=IiODT0HQrml84NH', about: 'FORMER LAW ENFORCEMENT CHAT, INACTIVE.'},
  {id: '12', name: 'NO TITLE cars buy/sell/trade San Andreas', date: '2024-06-09', online: 139, deleted: 16, link: 'https://chat.gta.world/?invite=Ltn14btaqnc7BcF', about: 'FORMER STOLEN CARS MARKETPLACE. NOW UNDERGROUND MARKETPLACE.'},
  {id: '13', name: 'Blue Eyes White Dragon', date: '2025-06-22', online: 34, deleted: 5, link: 'https://chat.gta.world/?invite=AKunRyGlDTyMrPN', about: ''},
  {id: '14', name: 'SEB (Keep it SFW)', date: '2024-01-30', online: 26, deleted: 5, link: 'https://chat.gta.world/?invite=EMazCbhIPwQmmWP', about: 'FORMER LAW ENFORCEMENT CHAT, INACTIVE.'},
  {id: '15', name: 'Make LS Trap Again 🔌', date: '2025-07-19', online: 41, deleted: 3, link: 'https://chat.gta.world/?invite=R1MLihoMzSgY8G0', about: ''},
  {id: '16', name: 'Medical Members LS', date: '2024-07-09', online: 24, deleted: 3, link: 'https://chat.gta.world/?invite=I3XZanHpENEqLDL', about: 'SHARED BY @CraccCG ON FACEBROWSER.'},
  {id: '17', name: 'Exotic Empire LS', date: '2024-07-21', online: 51, deleted: 7, link: 'https://chat.gta.world/?invite=6RbgSbo48bXt1PX', about: 'SHARED BY @trophiedupeight ON FACEBROWSER.'},
  {id: '18', name: 'vin.exchange', date: '2025-07-14', online: 27, deleted: 4, link: 'https://chat.gta.world/?invite=slbduQcDAfJt05M', about: 'SHARED BY @VinewoodM98 ON LS CHAT.'},
  {id: '19', name: 'LS STRAINS 🍃', date: '2024-04-23', online: 25, deleted: 4, link: 'https://chat.gta.world/?invite=AOiBYRkFgVwFksL', about: 'SHARED BY @pnut#5 ON LS CHAT.'},
  {id: '20', name: 'LSPICKS - BEST SPORT TIPSTER', date: '2024-07-09', online: 20, deleted: 5, link: 'https://chat.gta.world/?invite=nnvBZgE7SuNvOGW', about: 'SHARED BY @LSPICKS $$ ON LS CHAT.'},
  {id: '21', name: 'Mary Jane Lane', date: '2024-08-10', online: 377, deleted: 46, link: 'https://chat.gta.world/?invite=LXUdqUxppvB4yqL', about: 'SHARED BY @LS Medicals ON LS CHAT.'},
  {id: '22', name: 'LS Vendorz', date: '2024-08-05', online: 514, deleted: 2, link: 'https://chat.gta.world/?invite=LEq7e6n0RuCtRZc', about: 'SHARED BY @LS Medicals ON LS CHAT.'},
  {id: '23', name: 'Private Listings ((18+ RP))', date: '2025-03-14', online: 61, deleted: 5, link: 'https://chat.gta.world/?invite=ucS112OUDAVT72d', about: 'FORMER ESCORT ADS CHAT, INACTIVE. (( 18+ ))'},
  {id: '24', name: 'Shop wit da goat', date: '2025-09-24', online: 22, deleted: 3, link: 'https://chat.gta.world/?invite=H6azciPdKc29J3F', about: 'FORMERLY KNOWN AS "Gas Delivery". MARIJUANA DELIVERY SERVICE ESTABLISHED BY mota delivery. CASHTAP PAYMENTS.'},
  {id: '25', name: 'Hitman Services', date: '2025-10-13', online: 20, deleted: 4, link: 'https://chat.gta.world/?invite=w2VsGdJGXqmzYA7', about: 'HITMAN OFFERING CONTRACT KILLING SERVICES WITH PHOTO PROOF OF COMPLETITION.'}
];
